### ISSUE TITLE
Does the constructor argument name matter?

### ISSUE THREAD

**Issue by webcraft** [ShawnMcCool/laravel-auto-presenter#56]
Hi,

I'm using 3.0.0-beta7 on the latest L5 commit.

It seems to me that the argument name you give to the constructor of your Presenter class does really matter. It should be named $resource, if you call it $post (like the readme says) or $item or $whatever, it won't work. This is how it works for me:

```php
class PostPresenter extends BasePresenter
{
    public function __construct(Post $resource)
    {
        $this->wrappedObject = $resource;
    }
```

Is this by design, is this a bug, or is this me not using it correctly? The readme doesn't mention this.

Anyway, thanks for the awesome package!

**Comment by hardevine** [comment]
very helpful plz add to readme :+1:

**Comment by GrahamCampbell** [comment]
Done in #65.
