### ISSUE TITLE
[Proposal] A decorate() helper for when eager loading isn't possible

### ISSUE THREAD

**Issue by baileyparker** [ShawnMcCool/laravel-auto-presenter#59]
I'm curious about others' opinions on including a `decorate()` helper.

I've found that in some situations (especially when using complicated raw eloquent or db queries) it is difficult/unfeasible/impossible to eager load relationships.

To remedy this, I've created a little helper function that instantiates the `PresenterDecorator` and lazily decorates a model:

    function decorate($model) {
    	$decorator = App::make('McCool\LaravelAutoPresenter\PresenterDecorator');
    	return $decorator->decorate($model);
    }

Is this something that would be useful to PR or is there a better pattern for this?

**Comment by GrahamCampbell** [comment]
I really dislike helpers. Note that you can also do this:

```php
use McCool\LaravelAutoPresenter\Facades\AutoPresenter;

$decorated = AutoPresenter::decorate($model);
```

You can also alias that facade in your config.

**Comment by baileyparker** [comment]
Ah. I checked for a facade on my local version, but I hadn't recently `composer update`'d so I didn't see that there is now a facade for the decorator. This is helpful. Thanks!
