### ISSUE TITLE
Auto presenter does not decorate model in Controller

### ISSUE THREAD

**Issue by ludwigmair** [ShawnMcCool/laravel-auto-presenter#62]
Hi,
i discovered that the cool presenter package is not decorating a given model in a controller but in the views
i have tried something like this without  any result

$decorated_model = app('autopresenter')->decorate($plain_model);
with this i get a object with the right count on records in return but the records are empty

i use 
"mccool/laravel-auto-presenter": "~3.0@dev"

i hope for a fix or a workaround or tip

cheers and many thanks Ludwig

**Comment by GrahamCampbell** [comment]
Yeh, we've got no way to automatically do that. You can easily decorate your model/collection yourself though. We've even got a facade to make this as simple as possible. Here's a code example for you:

```php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Routing\Controller;
use McCool\LaravelAutoPresenter\Facades\AutoPresenter;

class FooController extends Controller
{
    public function example()
    {
        $posts = Post::all();

        $decorated = AutoPresenter::decorate($posts);

        // continue
    }
}
```

**Comment by ludwigmair** [comment]
Hi Graham,

fantastic, works great

thank you for this fast tip

cheers Ludwig

**Comment by GrahamCampbell** [comment]
No problem. :)
