### ISSUE TITLE
Don't support RESTful ?

### ISSUE THREAD

**Issue by foolmath** [ShawnMcCool/laravel-auto-presenter#69]
We need it to support RESTful, How can I do?

**Comment by GrahamCampbell** [comment]
Not got any idea what you mean? This package is for decorating your models. What else goes on in your application is up to you.

**Comment by foolmath** [comment]
Presenter can not take effect in the API

**Comment by GrahamCampbell** [comment]
Not sure what you mean. If you're not rendering a view, we can;t automatically present your models for you. There's nothing special or magic about laravel. It's just php code.

You can however, manually present your models using our facade, or by dependency injecting our presenter decorator class.

**Comment by foolmath** [comment]
Thinks
