### ISSUE TITLE
Lumen Support ?

### ISSUE THREAD

**Issue by RiseupDev** [ShawnMcCool/laravel-auto-presenter#70]
is this package supported by the new framework Lumen ?

**Comment by GrahamCampbell** [comment]
Yes, should do.

**Comment by GrahamCampbell** [comment]
Lumen is only for the more experienced though.

**Comment by RiseupDev** [comment]
Alright, you have some responses man that hurts :')

**Comment by GrahamCampbell** [comment]
Sorry - I wasn't trying to be rude. I was just trying to get the point across that if you are not experienced with laravel/php, Lumen IS a bad idea. I would hate for people to waste time using Luman when it's not suitable for them.

**Comment by RiseupDev** [comment]
I've used Laravel since version 3 (even it's different from 4+) and in many project so I know my way around, but thanks for the heads up :)

**Comment by GrahamCampbell** [comment]
Great. Enjoy Lumen. :)

**Comment by bharatsoftpro** [comment]
@GrahamCampbell how to install and configure with with Lumen 5.4
